name: wagon_wheel
description: A new Flutter package to create a custom wagon wheel widget for cricket applications.
version: 0.0.1
homepage: https://github.com/tauqeerkhattak/wagon_wheel.git

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: